### ISSUE TITLE
Secure Connection while Browsing

### ISSUE THREAD

**Issue by cchristelis** [kartoza/LBIMS#3]
# User Story

## Actor

All users

## Description

While the user is using the site, all traffic is SSL secured.

## Preconditions

- 

## Process Flow

1. The user has navigated to the site.

## Exceptions

1. Man in the Middle attacks etc.

## Business Rules

1. Can we use letsencrypt or are we going to get a authoroty to sign the certificate?

## Assumptions

1. The user uses a modern browser, which is able to handle the cipher, which is negotiated.

**Comment by gubuntu** [comment]
This issue was moved to kartoza/LEDET_BIMS#19
